### ISSUE TITLE
experiment with amChart library

### ISSUE THREAD

**Issue by moocunsw** [moocunsw/PVCE-QILT#12]
start with the spider charts; compare solution with highcharts and select an option

**Comment by whyes** [comment]
Converted spider charts to AmCharts : https://github.com/moocunsw/PVCE-QILT/commit/9ff2847224325c06405890b8ea44572b177f297f

From what I can see through using AmCharts, it is easier to set up than highcharts if the data frame is already in the correct format. Functionality wise, it seems to offer much of the same selections as highcharts.  Documentation (and online examples) for AmCharts is not as good as highcharts because it is not as popular, and this might cause troubles for debugging or changing a specific detail of the chart.

**Comment by moocunsw** [comment]
@whyes can we have an example of amCharts and highcharts for the spider chart and the bar chart with confidence intervals? (out of the template for now)

**Comment by whyes** [comment]
@moocunsw this is now on master in folder testCharts/App.R

**Comment by moocunsw** [comment]
the only feature which comes nicely out of the box with amChart seems to be the annotation tool, but we can add another library to annotate highcharts too, so i'm closing this
